apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: demo-go-gitops
  description: This is GitOps manifest for demo-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: demo-go
    backstage.io/kubernetes-id: demo-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: demo-go   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:demo-go
